myblog/blueprints/admin.py
from flask import Blueprint, redirect, url_for, flash, render_template, abort
from flask_login import current_user
from myblog.forms import NewPostForm
from myblog.models import BlogPost, Comment
from myblog.extensions import db
from datetime import date
from functools import wraps

admin_bp = Blueprint("admin", __name__)


def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.role != "admin":
            return abort(403)
        return f(*args, **kwargs)
    return decorated_function


@admin_bp.route("/new_post", methods=["GET", "POST"])
@admin_only
def create_post():
    if not current_user.is_authenticated:
        return redirect(url_for('blog.home'))
    form = NewPostForm()
    if form.validate_on_submit():
        new_post = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            img_url=form.img_url.data,
            author=current_user,
            date=date.today().strftime("%B %d, %Y"),
            body=form.body.data
        )
        db.session.add(new_post)
        db.session.commit()
        flash("Post successfully added.", "warning")
        return redirect(url_for("blog.home"))
    return render_template('new_post.html', form=form, title="Create Post")


@admin_bp.route("/edit_post/<int:post_id>", methods=["GET", "POST"])
@admin_only
def edit_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    form = NewPostForm(
        title=post.title,
        subtitle=post.subtitle,
        img_url=post.img_url,
        author=current_user,
        body=post.body
    )
    if form.validate_on_submit():
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.img_url = form.img_url.data
        post.body = form.body.data
        db.session.commit()
        return redirect(url_for("blog.show_post", post_id=post.id))
    return render_template("new_post.html", form=form, edit_post=True, title="Edit Post")


@admin_bp.route("/delete_post/<int:post_id>")
@admin_only
def delete_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('blog.home'))


@admin_bp.route("/delete_comment/<int:comment_id>")
@admin_only
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('blog.show_post', post_id=comment.post_id))

myblog/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from flask_login import current_user, login_user, logout_user, login_required
from myblog.models import User
from myblog.forms import RegisterForm, LoginForm, RequestResetForm, ResetPasswordForm, ChangeUsernameForm
from myblog.extensions import db, bcrypt, login_manager, oauth
from myblog.tasks import send_mail
from myblog.utils import random_string_generator
from werkzeug.security import check_password_hash

auth_bp = Blueprint("auth", __name__)


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(int(user_id))


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('blog.home'))
    form = RegisterForm()
    if request.method == "POST" and form.validate():
        if User.query.filter_by(email=form.email.data.lower()).first():
            flash("You've already signed up with that email, log in instead!", "danger")
            return render_template('register.html', form=form)
        if User.query.filter_by(name=form.username.data).first():
            flash(f"Username {form.username.data} is already taken", "danger")
            return render_template('register.html', form=form)
        secured_password = bcrypt.generate_password_hash(form.password.data, 15).decode('utf-8')
        new_user = User(
            email=form.email.data.lower(),
            password=secured_password,
            name=form.username.data,
        )

        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        flash(f"Successfully created user \"{form.username.data}\"", "warning")
        return redirect(url_for('blog.home'))
    return render_template('register.html', form=form, title="Register")


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.home'))
    form = LoginForm()
    if request.method == "POST":
        user = User.query.filter_by(email=form.email.data.lower()).first()
        # ######################## REHASHING IF NEEDED ##################### #
        if user and user.needs_rehash and check_password_hash(user.password, form.password.data):
            user.password = bcrypt.generate_password_hash(form.password.data)
            user.needs_rehash = False
            db.session.commit()
        # ################################################################## #
        if user and not user.needs_rehash and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash(f"Successfully logged in as {user.name}", "warning")
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('blog.home'))
        else:
            flash("Wrong email or password. Try again", "danger")
    return render_template('login.html', form=form, title="Login")


@auth_bp.route('/account', methods=["GET", "POST"])
@login_required
def account():
    form = ChangeUsernameForm()
    if request.method == "POST" and form.validate():
        if User.query.filter_by(name=form.username.data).first():
            flash(f"Username {form.username.data} is already taken", "danger")
            return redirect(url_for('auth.account'))
        current_user.name = form.username.data
        db.session.commit()
        flash("Your username has been updated!", "warning")
        return redirect(url_for('auth.account'))
    return render_template('account.html',
                           eligible_for_change=current_user.name[0:5] == "User-",
                           form=form,
                           title='Account')


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Successfully logged out", "warning")
    return redirect(url_for('blog.home'))


@auth_bp.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        form = RequestResetForm(email=current_user.email)
    else:
        form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_mail(subject='myBlog - Password Reset Request',
                      to=user.email,
                      body=f'''To reset your password, please follow the link bellow:
{url_for('auth.reset_token', token=user.get_reset_token(), _external=True)}
If you did not make this request then simply ignore this email and no changes will be made.
''')
            flash("Check Your email for further instructions. Token expires after 10 minutes.", "warning")
            return redirect(url_for('auth.login'))
        else:
            flash("No account exists at this email address", "danger")
    return render_template('reset_request.html', form=form, title='Reset Password')


@auth_bp.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    user = User.verify_reset_token(token=token)
    if user is None:
        flash("This is invalid or expired token. Please try again.", 'danger')
        return redirect(url_for('auth.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.password.data, 15).decode('utf-8')
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "warning")
        return redirect(url_for('auth.login'))
    return render_template('change_password.html', form=form, title="Reset Password")


@auth_bp.route('/google/')
def google():
    oauth.register(
        name='google',
        client_id=current_app.config['GOOGLE_CLIENT_ID'],
        client_secret=current_app.config['GOOGLE_CLIENT_SECRET'],
        server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',
        client_kwargs={
            'scope': 'openid email profile'
        }
    )

    redirect_uri = url_for('auth.google_auth', _external=True)
    return oauth.google.authorize_redirect(redirect_uri)


@auth_bp.route('/google/auth/', methods=["GET", "POST"])
def google_auth():
    token = oauth.google.authorize_access_token()
    user = User.query.filter_by(email=token['userinfo']['email']).first()
    if user:
        login_user(user)
        flash(f"Successfully logged in as {user.name}", "warning")
        return redirect(url_for('blog.home'))
    else:
        random_password = bcrypt.generate_password_hash(random_string_generator(32), 15).decode('utf-8')
        new_user = User(
            email=token['userinfo']['email'],
            password=random_password,
            name=f"User-{random_string_generator(6)}",
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        flash(f"Successfully logged in as {new_user.name}", "warning")
    return redirect(url_for('blog.home'))

myblog/blueprints/blog.py
from flask import Blueprint, render_template, redirect, flash, url_for, request, current_app
from flask_login import current_user
from myblog.models import BlogPost, Comment
from myblog.forms import ContactForm, CommentForm
from myblog.extensions import db
from myblog.tasks import send_mail, get_sidebar_news
import os

blog_bp = Blueprint("blog", __name__)


@blog_bp.route("/")
@blog_bp.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts_per_page = current_app.config['POSTS_PER_PAGE']
    posts = BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page, per_page=posts_per_page)
    return render_template("index.html", posts=posts)


@blog_bp.route("/about")
def about():
    return render_template("about.html", title="About")


@blog_bp.route("/contact", methods=["GET", "POST"])
def contact():
    if current_user.is_authenticated:
        form = ContactForm(name=current_user.name, email=current_user.email)
    else:
        form = ContactForm()

    if form.validate_on_submit():
        send_mail(
            subject='Hello from MyBlog Contact Form',
            to=os.environ.get("MAIL_USER"),
            body=f'''
            Name: {form.name.data}
            E-mail: {form.email.data}
            Message: {form.text.data}'''
        )
        flash("Thank You for your message.", "warning")
        return redirect(url_for('blog.home'))
    return render_template("contact.html", form=form, title="Contact Me")


@blog_bp.route("/post/<int:post_id>", methods=["GET", "POST"])
def show_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    comment_form = CommentForm()
    if request.method == "POST" and comment_form.validate():
        if not current_user.is_authenticated:
            flash("You need to login or register to comment.", "warning")
            return redirect(url_for("auth.login"))
        else:
            new_comment = Comment(
                text=comment_form.text.data,
                comment_author=current_user,
                commented_post=post
            )
            db.session.add(new_comment)
            db.session.commit()
    return render_template('post.html', post=post, comment_form=comment_form)


@blog_bp.app_context_processor
def sidebar_news():
    return dict(sidebar_news=get_sidebar_news())

myblog/templates/_pagination.html
<!-- Pagination Links-->
<div class="text-center">
    <a href="{{ url_for('blog.home', page=posts.prev_num) }}"
       class="btn btn-outline-dark
       {% if posts.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if posts.page == page_num %}
            <a href="{{ url_for('blog.home', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('blog.home', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('blog.home', page=posts.next_num) }}"
       class="btn btn-outline-dark
       {% if posts.page == posts.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-center m-3">
   Showing page {{ posts.page }} of {{ posts.pages }}
</p>

myblog/templates/_sidebar.html
<div class="content-section">
    <h3 class="text-center">Sidebar</h3>
    <p class='text-muted-light text-center py-2'>USEFUL LINKS</p>
    <ul class="list-group">
        <li class="list-group-item list-group-item-light">
            <a href="https://github.com/Jacek89/myBlog">GitHub repository</a>
        </li>
        <li class="list-group-item list-group-item-light">
            <a href="https://www.python.org/">Python.org</a>
        </li>
        <li class="list-group-item list-group-item-light">
            <a href="https://flask.palletsprojects.com/en/2.2.x/">Flask Documentation</a>
        </li>
    </ul>
    <p class='text-muted-light text-center pb-2 pt-4'>NEWS: TOP HEADLINES</p>
    <ul class="list-group">
        {% if sidebar_news == 'fail' %}
            <li class="list-group-item list-group-item-light">Something went wrong...</li>
        {% else %}
            {% for article in sidebar_news %}
            <li class="list-group-item list-group-item-light">
                <a href="{{ article['url'] }}">{{ article['title'] }}</a>
            </li>
            {% endfor %}
        {% endif %}
    </ul>
</div>

myblog/templates/about.html
{% extends "base.html" %}
{% block content %}
<h4 class="border-bottom mb-4">About</h4>
<div class="content p-3">
    <p class="pb-2">This website has been created for educational purposes. It can be successfully used as a personal blog and be expanded. During the development of this web application, I studied a lot about how websites work. The main topics I learned: </p>
        <ul>
            <li>Bootstrap to create basic front-end</li>
            <li>Flask framework and files structure for such an application</li>
            <li>CRUD operations with Flask and SQLalchemy</li>
            <li>SQL models with links</li>
            <li>PostgreSQL database management, migrations, pgAdmin 4</li>
            <li>utilize small flask modules to improve application</li>
            <li>authentication system, handling with user and admin permissions</li>
            <li>Google authorization</li>
            <li>the idea of passwords hashing and implementing it to a website</li>
            <li>sending reset password mails with tokens via JWT</li>
            <li>using cache to store temporary data with Redis</li>
            <li>async functions like sending emails, foundations of Celery with Redis</li>
        </ul>
</div>
{% endblock %}

myblog/templates/account.html
{% extends "base.html" %}
{% block content %}
<h4 class="border-bottom mb-4">Your Account</h4>
<div class="content">
    <div class="row">
        <div class="col-sm-4 text-center">
            <div class="profile-image m-3">
                <img src="{{ current_user.email | gravatar}}">
            </div>
            <div class="fs-4 fw-bold">
                {{ current_user.name }}
            </div>
            <div class="text-muted pb-3">
                <small>{{ current_user.email }}</small>
            </div>
        </div>
        <div class="col-sm-8" style="padding:0 3%;">
            <div class="fw-bold pb-3">
                Account Options
            </div>
            {% if eligible_for_change %}
            <form method="POST" action="">
            {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}
                    <div class="form-group">
                        {{ form.submit(class="btn btn-secondary btn-sm", style="float: right;") }}
                    </div>
                    <div class="form-text">
                        Your username must be 3-20 characters long. <br>
                        <span class="text-danger">
                            Warning! You can change your username only once, because your name was generated automatically.
                        </span>
                    </div>
                </div>
             </form>
            {% endif %}
            <a href="{{ url_for('auth.reset_request') }}"><p>Change Password</p></a>
            <a href="https://pl.gravatar.com/"><p class="py-1"> Change Avatar - gravatar.com</p></a>
            <hr>
            <p>Posts: {{ current_user.posts | length }}</p>
            <p class="py-1">Comments: {{ current_user.comments | length }}</p>
        </div>
    </div>
</div>
{% endblock %}

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% if title %}
            myBlog - {{ title  }}
        {% else %}
            myBlog
        {%endif %}
    </title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Montserrat:wght@400;900&family=Sacramento&family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {{ moment.include_moment() }}
</head>
<body>
<div class ="bg-dark">
    <div class="container-fluid container-website">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{{ url_for('blog.home') }}">myBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                <ul class="navbar-nav me-auto">
                     <li class="nav-item">
                         <a class="nav-link" href="{{ url_for('blog.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.contact') }}">Contact</a>
                    </li>
                        {% if current_user.role == "admin": %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('admin.create_post') }}">New Post</a>
                            </li>
                        {% endif %}
                </ul>

                <ul class="navbar-nav ms-auto">
                    {% if not current_user.is_authenticated: %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.account') }}">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        </li>
                    {% endif %}
                </ul>


            </div>
        </nav>
    </div>
</div>
<div class="container-fluid container-website">
    <div class="row">
        <div class="col-md-8 main-content">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                         </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-md-4 sidebar">
          {% include '_sidebar.html' %}
        </div>
    </div>
</div>
<footer>
    <div class="text-center p-3 bg-dark text-white footer">
        © 2022 Copyright
    </div>
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</body>
</html>

myblog/templates/change_password.html
{% extends "base.html" %}
{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <h4 class="border-bottom mb-4">Reset Password</h4>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                <div class="form-text">
                    Your password must be at least 8 characters long.
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn-custom") }}
        </div>
    </form>
{% endblock %}

myblog/templates/contact.html
{% extends "base.html" %}
{% block content %}
 <form method="POST" action="">
     {{ form.hidden_tag() }}
     <h4 class="border-bottom mb-4">Contact Me</h4>
     <div class="form-group">
         {{ form.name.label(class="form-control-label") }}
         {{ form.name(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.email.label(class="form-control-label") }}
         {{ form.email(class="form-control form-control-lg") }}
     </div>
          <div class="form-group">
         {{ form.text.label(class="form-control-label") }}
         {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn-custom") }}
     </div>
 </form>
{% endblock %}

myblog/templates/index.html
{% extends "base.html" %}
{% block content %}

{% for post in posts.items %}
<div class="post-preview">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <a href="{{ url_for('blog.show_post', post_id=post.id) }}">
                    <img class="post-preview-img" src="{{ post.img_url }}">
                </a>
            </div>
            <div class="col-lg-8">
                <a href="{{ url_for('blog.show_post', post_id=post.id) }}">
                    <h3 class="post-title">
                          {{post.title}}
                    </h3>
                    <p class="post-subtitle py-1">
                          {{post.subtitle}}
                    </p>
                </a>
                    <hr class="post-preview-hr">
                    <p class="post-meta pb-2">Posted by {{post.author.name}} in {{ post.date }}

                    </p>
            </div>
        </div>
    </div>
</div>
{% if not loop.last %}
    <hr>
{% endif %}

{% endfor %}

{% include '_pagination.html' %}

{% endblock %}

myblog/templates/login.html
{% extends "base.html" %}
{% block content %}
 <form method="POST" action="">
     {{ form.hidden_tag() }}
     <h4 class="border-bottom mb-4">Login</h4>
     <div class="form-group">
         {{ form.email.label(class="form-control-label") }}
         {{ form.email(class="form-control form-control-lg") }}
     </div>
          <div class="form-group">
         {{ form.password.label(class="form-control-label") }}
         {{ form.password(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn-custom") }}
         <a href="{{ url_for('auth.reset_request') }}" class="ps-2"><small>Forgot Password?</small></a>
     </div>
     <hr>
     <div class="text-center pb-3">
         <a href="{{url_for('auth.google') }}">
             <img src="{{ url_for('static', filename='images/btn_google_signin_dark_focus_web.png') }}">
         </a>
     </div>
 </form>
{% endblock %}

myblog/templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="post-preview">
    <div class="container pb-3">
        <div class="post-meta pb-2">
                Posted by {{post.author.name}} in {{ post.date }}
                {% if current_user.role == "admin": %}
                    <div style="float:right;">
                        <a href="{{ url_for('admin.edit_post', post_id=post.id) }}">
                            <button type="button" class="btn btn-secondary btn-sm ms-auto">Edit</button>
                        </a>
                        <a href="{{ url_for('admin.delete_post', post_id=post.id) }}">
                            <button type="button" class="btn btn-danger btn-sm">Delete</button>
                        </a>
                    </div>
                {% endif %}
        </div>
        <hr class="post-preview-hr">
        <h2 class="post-title pb-3 pt-2">
            {{post.title}}
        </h2>
        <div class="post-subtitle" style="font-weight: bold;">
            {{post.subtitle}}
        </div>
        <div class="post-body">
            {{ post.body|safe }}
        </div>
    </div>
</div>
<!--Comments section-->
<div class="comment-title-bar py-2 ps-3">
    {% if post.post_comments|length == 1 %}
        <h4>1 Comment</h4>
    {% else %}
        <h4>{{ post.post_comments|length }} Comments</h4>
    {% endif %}
</div>
{% if current_user.is_authenticated %}
    <form method="POST" action="">
        {{ comment_form.hidden_tag() }}
            <div class="form-group">
                {{ comment_form.text.label(class="form-control-label") }}
                {{ comment_form.text(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ comment_form.submit(class="btn-custom btn-sm") }}
            </div>
    </form>
{% else %}
    <p class="p-3 text-center fw-bold">
        You have to be signed in to add comments.
        <a class="text-muted" href="{{ url_for('auth.login') }}">Login</a> or
        <a class="text-muted" href="{{ url_for('auth.register') }}">Register</a>
    </p>
{% endif %}
{% if post.post_comments %}
    <div class="comment-box">
        {% for comment in post.post_comments %}
            <div class="comment-image">
                <img src="{{ comment.comment_author.email | gravatar}}">
            </div>
            <div class="comment-author text-muted">
                <small>{{ comment.comment_author.name }}</small>
                {% if current_user.role == "admin": %}
                    <small>
                        <a style="color: red;" href="{{ url_for('admin.delete_comment', comment_id=comment.id) }}">✘</a>
                    </small>
                {% endif %}
                <small style="float: right; margin-right: 2.5%">{{ moment(comment.created_at).fromNow() }}</small>
            </div>
            <div class="comment">
                {{ comment.text }}
            </div>
            <br>
        {% endfor %}
    </div>
{% endif %}

{% endblock %}

myblog/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <h4 class="border-bottom mb-4">Reset Password</h4>
    <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if current_user.is_authenticated: %}
            {{ form.email(class="form-control form-control-lg", disabled=True) }}
        {% else: %}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        {% endif %}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn-custom") }}
     </div>
 </form>
{% endblock %}